replicaCount: 2

image:
  repository: registry.example.com/mlops/model-svc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Simple canary: split replicas (80/20)
deployment:
  stableReplicas: 4
  canaryReplicas: 1

env:
  - name: MODEL_PATH
    value: /app/models/model.joblib
  - name: META_PATH
    value: /app/models/metadata.json
